apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-audit-config
  namespace: vault
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush         5
      Log_Level     info
      Parsers_File  parsers.conf

    # File audit device
    [INPUT]
      Name              tail
      Tag               vault.audit.file
      Path              /vault/audit/audit.log
      Parser            json
      Mem_Buf_Limit     50MB
      Skip_Long_Lines   On
      Refresh_Interval  5

    # Socket audit device
    [INPUT]
      Name              forward
      Tag               vault.audit.sock
      Unix_Path         /vault/audit/fluentbit.sock

    # Optional redaction of sensitive request bodies
    [FILTER]
      Name              modify
      Match             vault.audit.*
      Remove_regex      request.data\..*

    [OUTPUT]
      Name                cloudwatch_logs
      Match               vault.audit.*
      region              ${AWS_REGION}
      log_group_name      /aws/eks/vault/audit
      log_stream_prefix   pod-
      auto_create_group   true

  parsers.conf: |
    [PARSER]
      Name    json
      Format  json
